### ISSUE TITLE
Requires Due board configuration rather than M2 board configuration

### ISSUE THREAD

**Issue by adamvoss** [collin80/M2RET#2]
Macchina has published [a custom board configuration for the Arduino IDE](https://github.com/macchina/arduino-boards-sam).  Because that configuration uses different pin [array index] numbers, sketches (such as M2RET) which utilize `SamNonDuePin` will not work because Due-based numbers are used.

Is switching to use the M2 board configuration on M2RET's roadmap and/or wold you consider merging a pull request making the change?

**Comment by collin80** [comment]
Yeah, I suppose that is problematic. Looks like I'll have to switch it over to the custom board definition numbers.

**Comment by collin80** [comment]
This should be corrected now. Removed dependency on SamNonDuePin and added dependency on compiling with the custom board files. Also, I updated the README to show the change. I also updated the readme to point to the Macchina repos where I could. Currently the Macchina repos do not have the SD_HSCMI library and the single wire CAN library has different file names so that won't directly work either.

**Comment by adamvoss** [comment]
Awesome, thanks!

FWIW, `SD_HSCMI` is now included in [Arduino_Due_SD_HSMCI](https://github.com/macchina/Arduino_Due_SD_HSMCI) which is how it was originally packaged up-stream.  I will work on single-wire CAN, my intention is to do what you recommended somewhere and split the SWCAN enabling code from the rest of the mcp2515 library (such that the SWCAN library will depend on mcp2515).  I just need to find the time to do it.  I'll submit a PR here when I've done so.
